### ISSUE TITLE
High CPU usage.

### ISSUE THREAD

**Issue by XephyLon** [goaaats/FFXIVRichPresence#2]
Just as the title says, I ran the `FFXIVRichPresenceRunner.exe` and it uses more CPU than the game itself.

**Comment by goaaats** [comment]
Someone already told me about this one, I'll look into it over the next few days - thanks for the heads-up!

**Comment by goaaats** [comment]
Found a fix, stupid mistake, I'll push a new version shortly. Usage is basically 0 now.

**Comment by goaaats** [comment]
https://github.com/goaaats/FFXIVRichPresence/releases/tag/1.2
