### ISSUE TITLE
Updating to support 4.5?

### ISSUE THREAD

**Issue by XephyLon** [goaaats/FFXIVRichPresence#3]
Just as the title says. Any plans on updating the app to support the new FF patch?

**Comment by goaaats** [comment]
I already fixed it, but xivapi requires an API key for all requests now, still debating on whether I should just include it. Might push that version later today.

**Comment by goaaats** [comment]
https://github.com/goaaats/FFXIVRichPresence/releases/latest

**Comment by XephyLon** [comment]
Doesn't work since the release of 4.55

Yeah, the usual....

**Comment by goaaats** [comment]
I tested this when it released, should be working fine - can you show me the error message?

**Comment by XephyLon** [comment]
There's no error message. I just open the exe and nothing happens. So I simply assumed it's not working as this is how it always acted when it needed fixing.

**Comment by amparagas** [comment]
To add to this, I noticed there was some error log, I too am getting the same behavior.
Nhaama just needs to get updated?

`System.Exception: Could not get definitions for version: https://raw.githubusercontent.com/goaaats/Nhaama/master/definitions/FFXIV/dx11/2019.02.14.0000.0000.json ---> System.Net.WebException: The remote server returned an error: (404) Not Found.`

**Comment by goaaats** [comment]
Should be fixed with https://github.com/goaaats/Nhaama/commit/d016b1ada73a9828f790de8602b88f3121a78e94, sorry about that - been a bit busy. Don't need to redownload.
